### ISSUE TITLE
Add "phpparser" task to grumphp's config

### ISSUE THREAD

**Issue by vyshkant** [vyfony/filterable-table-bundle#10]
Add this task to grumphp.yml when https://github.com/phpro/grumphp/issues/508 is resolved. Also run `composer require --dev nikic/php-parser`.

```yaml
phpparser:
  visitors:
    declare_strict_types: ~
    forbidden_function_calls:
      blacklist:
      - 'var_dump'
    no_exit_statements: ~
  metadata:
    priority: -85
```
